# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_hist_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 406)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.incoming_connections_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.incoming_connections_checkbox.setObjectName("incoming_connections_checkbox")
        self.gridLayout_2.addWidget(self.incoming_connections_checkbox, 1, 1, 1, 1)
        self.filter_num_partner_nodes_label = QtWidgets.QLabel(self.centralwidget)
        self.filter_num_partner_nodes_label.setObjectName("filter_num_partner_nodes_label")
        self.gridLayout_2.addWidget(self.filter_num_partner_nodes_label, 4, 0, 1, 1)
        self.filter_num_partner_nodes_textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.filter_num_partner_nodes_textbox.setObjectName("filter_num_partner_nodes_textbox")
        self.gridLayout_2.addWidget(self.filter_num_partner_nodes_textbox, 4, 1, 1, 1)
        self.outgoing_connections_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.outgoing_connections_checkbox.setObjectName("outgoing_connections_checkbox")
        self.gridLayout_2.addWidget(self.outgoing_connections_checkbox, 2, 1, 1, 1)
        self.fetch_skiddata_button = QtWidgets.QPushButton(self.centralwidget)
        self.fetch_skiddata_button.setObjectName("fetch_skiddata_button")
        self.gridLayout_2.addWidget(self.fetch_skiddata_button, 4, 3, 1, 1)
        self.connections_label = QtWidgets.QLabel(self.centralwidget)
        self.connections_label.setObjectName("connections_label")
        self.gridLayout_2.addWidget(self.connections_label, 1, 0, 1, 1)
        self.enter_skid_textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_skid_textbox.setObjectName("enter_skid_textbox")
        self.gridLayout_2.addWidget(self.enter_skid_textbox, 0, 1, 1, 1)
        self.skeleton_id_label = QtWidgets.QLabel(self.centralwidget)
        self.skeleton_id_label.setObjectName("skeleton_id_label")
        self.gridLayout_2.addWidget(self.skeleton_id_label, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.neuron_type1_label = QtWidgets.QLabel(self.centralwidget)
        self.neuron_type1_label.setObjectName("neuron_type1_label")
        self.horizontalLayout_7.addWidget(self.neuron_type1_label)
        self.neuron_type1_box = QtWidgets.QComboBox(self.centralwidget)
        self.neuron_type1_box.setEditable(False)
        self.neuron_type1_box.setObjectName("neuron_type1_box")
        self.neuron_type1_box.addItem("")
        self.neuron_type1_box.setItemText(0, "")
        self.neuron_type1_box.addItem("")
        self.neuron_type1_box.addItem("")
        self.neuron_type1_box.addItem("")
        self.neuron_type1_box.addItem("")
        self.neuron_type1_box.addItem("")
        self.neuron_type1_box.addItem("")
        self.horizontalLayout_7.addWidget(self.neuron_type1_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pb_glom_label = QtWidgets.QLabel(self.centralwidget)
        self.pb_glom_label.setObjectName("pb_glom_label")
        self.horizontalLayout_8.addWidget(self.pb_glom_label)
        self.pb_glom_box = QtWidgets.QComboBox(self.centralwidget)
        self.pb_glom_box.setObjectName("pb_glom_box")
        self.pb_glom_box.addItem("")
        self.pb_glom_box.setItemText(0, "")
        self.pb_glom_box.addItem("")
        self.pb_glom_box.addItem("")
        self.pb_glom_box.addItem("")
        self.pb_glom_box.addItem("")
        self.horizontalLayout_8.addWidget(self.pb_glom_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.plot_ring_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.plot_ring_check_box.setObjectName("plot_ring_check_box")
        self.verticalLayout_3.addWidget(self.plot_ring_check_box)
        self.plot_hist_button = QtWidgets.QPushButton(self.centralwidget)
        self.plot_hist_button.setObjectName("plot_hist_button")
        self.verticalLayout_3.addWidget(self.plot_hist_button)
        self.plotarea = QtWidgets.QWidget(self.centralwidget)
        self.plotarea.setObjectName("plotarea")
        self.verticalLayout_3.addWidget(self.plotarea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.incoming_connections_checkbox.setText(_translate("MainWindow", "Incoming"))
        self.filter_num_partner_nodes_label.setText(_translate("MainWindow", " Filter num of partner nodes:"))
        self.outgoing_connections_checkbox.setText(_translate("MainWindow", "Outgoing"))
        self.fetch_skiddata_button.setText(_translate("MainWindow", "Submit"))
        self.connections_label.setText(_translate("MainWindow", "Connections:"))
        self.skeleton_id_label.setText(_translate("MainWindow", "Enter skeleton id:"))
        self.neuron_type1_label.setText(_translate("MainWindow", "Neuron type 1: "))
        self.neuron_type1_box.setItemText(1, _translate("MainWindow", "P-EN1"))
        self.neuron_type1_box.setItemText(2, _translate("MainWindow", "P-EN2"))
        self.neuron_type1_box.setItemText(3, _translate("MainWindow", "P-EG"))
        self.neuron_type1_box.setItemText(4, _translate("MainWindow", "E-PG"))
        self.neuron_type1_box.setItemText(5, _translate("MainWindow", "G-E"))
        self.neuron_type1_box.setItemText(6, _translate("MainWindow", "Bidirectional Ring"))
        self.pb_glom_label.setText(_translate("MainWindow", "PB Glom 1: "))
        self.pb_glom_box.setItemText(1, _translate("MainWindow", "None"))
        self.pb_glom_box.setItemText(2, _translate("MainWindow", "PBG5"))
        self.pb_glom_box.setItemText(3, _translate("MainWindow", "PBG6"))
        self.pb_glom_box.setItemText(4, _translate("MainWindow", "PBG7"))
        self.plot_ring_check_box.setText(_translate("MainWindow", "Plot Ring Neurons"))
        self.plot_hist_button.setText(_translate("MainWindow", "Plot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

